<?xml version="1.0" encoding="UTF-8"?>

    <wsdl:service name="MathUtils">
        <wsdl:port name="MathUtilsHttpSoap11Endpoint" binding="ns:MathUtilsSoap11Binding">
            <soap:address location="http://localhost:8080/axis2/services/MathUtils"/>
        </wsdl:port>
        <wsdl:port name="MathUtilsHttpSoap12Endpoint" binding="ns:MathUtilsSoap12Binding">
            <soap12:address location="http://localhost:8080/axis2/services/MathUtils"/>
        </wsdl:port>
        <wsdl:port name="MathUtilsHttpEndpoint" binding="ns:MathUtilsHttpBinding">
            <http:address location="http://localhost:8080/axis2/services/MathUtils"/>
        </wsdl:port>
    <wsdl:service>

