[{class,
    [{name, "VoDKATV"},
     {constraints, [{invariants, []}]},
     {attributes,
        [{attribute,
            [{name, "state_rooms"}, {type, [{name, "Sequence(String)"}]}]}]},
     {operations,
        [{operation,
            [{name, "CreateRoom"},
             {params,
                [{param, [{name, "roomId"}, {type, [{name, "string"}]}]},
                 {param, [{name, "description"}, {type, [{name, "string"}]}]}]},
             {constraints,
                [{preconditions, []},
                 {postconditions,
                    [{constraint,
                        [{name, "CreateRoom"},
                         {body,
                            [{expression, "IfExp"},
                             {condition,
                                [{expression, "OperationCallExp"},
                                 {name, ""},
                                 {referredOperation, [{name, "or"}, {type, [{name, "Boolean"}]}]},
                                 {contents,
                                    [{content,
                                        [{expression, "OperationCallExp"},
                                         {name, ""},
                                         {referredOperation,
                                            [{name, "="}, {type, [{name, "Boolean"}]}]},
                                         {contents,
                                            [{content,
                                                [{expression, "VariableExp"},
                                                 {referredVariable,
                                                    [{expression, "Variable"},
                                                     {name, "roomId"},
                                                     {type, [{name, "string"}]}]}]},
                                             {content,
                                                [{expression, "StringLiteralExp"},
                                                 {value, ""}]}]}]},
                                     {content,
                                        [{expression, "OperationCallExp"},
                                         {name, ""},
                                         {referredOperation,
                                            [{name, "="}, {type, [{name, "Boolean"}]}]},
                                         {contents,
                                            [{content,
                                                [{expression, "VariableExp"},
                                                 {referredVariable,
                                                    [{expression, "Variable"},
                                                     {name, "roomId"},
                                                     {type, [{name, "string"}]}]}]},
                                             {content,
                                                [{expression, "UndefinedLiteralExp"},
                                                 {value, null}]}]}]}]}]},
                             {then,
                                [{expression, "OperationCallExp"},
                                 {name, ""},
                                 {referredOperation, [{name, "and"}, {type, [{name, "Boolean"}]}]},
                                 {contents,
                                    [{content,
                                        [{expression, "OperationCallExp"},
                                         {name, ""},
                                         {referredOperation,
                                            [{name, "and"}, {type, [{name, "Boolean"}]}]},
                                         {contents,
                                            [{content,
                                                [{expression, "OperationCallExp"},
                                                 {name, ""},
                                                 {referredOperation,
                                                    [{name, "and"}, {type, [{name, "Boolean"}]}]},
                                                 {contents,
                                                    [{content,
                                                        [{expression, "OperationCallExp"},
                                                         {name, ""},
                                                         {referredOperation,
                                                            [{name, "and"},
                                                             {type, [{name, "Boolean"}]}]},
                                                         {contents,
                                                            [{content,
                                                                [{expression, "OperationCallExp"},
                                                                 {name, ""},
                                                                 {referredOperation,
                                                                    [{name, "and"},
                                                                     {type, [{name, "Boolean"}]}]},
                                                                 {contents,
                                                                    [{content,
                                                                        [{expression,
                                                                            "OperationCallExp"},
                                                                         {name, ""},
                                                                         {referredOperation,
                                                                            [{name, "="},
                                                                             {type,
                                                                                [{name,
                                                                                    "Boolean"}]}]},
                                                                         {contents,
                                                                            [{content,
                                                                                [{expression,
                                                                                    "PropertyCallExp"},
                                                                                 {source,
                                                                                    [{expression,
                                                                                        "VariableExp"},
                                                                                     {referredVariable,
                                                                                        [{expression,
                                                                                            "Variable"},
                                                                                         {name,
                                                                                            "self"},
                                                                                         {type,
                                                                                            [{name,
                                                                                                "VoDKATV"}]}]}]},
                                                                                 {referredProperty,
                                                                                    [{name,
                                                                                        "state_rooms"},
                                                                                     {type,
                                                                                        [{name,
                                                                                            "Sequence(String)"}]}]}]},
                                                                             {content,
                                                                                [{expression,
                                                                                    "OperationCallExp"},
                                                                                 {name, "atPre"},
                                                                                 {referredOperation,
                                                                                    [{name,
                                                                                        "atPre"},
                                                                                     {type,
                                                                                        [{name,
                                                                                            "Sequence(String)"}]}]},
                                                                                 {contents,
                                                                                    [{content,
                                                                                        [{expression,
                                                                                            "PropertyCallExp"},
                                                                                         {source,
                                                                                            [{expression,
                                                                                                "VariableExp"},
                                                                                             {referredVariable,
                                                                                                [{expression,
                                                                                                    "Variable"},
                                                                                                 {name,
                                                                                                    "self"},
                                                                                                 {type,
                                                                                                    [{name,
                                                                                                        "VoDKATV"}]}]}]},
                                                                                         {referredProperty,
                                                                                            [{name,
                                                                                                "state_rooms"},
                                                                                             {type,
                                                                                                [{name,
                                                                                                    "Sequence(String)"}]}]}]}]}]}]}]},
                                                                     {content,
                                                                        [{expression,
                                                                            "OperationCallExp"},
                                                                         {name, ""},
                                                                         {referredOperation,
                                                                            [{name, "="},
                                                                             {type,
                                                                                [{name,
                                                                                    "Boolean"}]}]},
                                                                         {contents,
                                                                            [{content,
                                                                                [{expression,
                                                                                    "OperationCallExp"},
                                                                                 {name, ""},
                                                                                 {referredOperation,
                                                                                    [{name, "size"},
                                                                                     {type,
                                                                                        [{name,
                                                                                            "Integer"}]}]},
                                                                                 {contents,
                                                                                    [{content,
                                                                                        [{expression,
                                                                                            "PropertyCallExp"},
                                                                                         {source,
                                                                                            [{expression,
                                                                                                "VariableExp"},
                                                                                             {referredVariable,
                                                                                                [{expression,
                                                                                                    "Variable"},
                                                                                                 {name,
                                                                                                    "result"},
                                                                                                 {type,
                                                                                                    [{name,
                                                                                                        "createRoomResponse"}]}]}]},
                                                                                         {referredProperty,
                                                                                            [{name,
                                                                                                "errors"},
                                                                                             {type,
                                                                                                [{name,
                                                                                                    "Sequence(error)"}]}]}]}]}]},
                                                                             {content,
                                                                                [{expression,
                                                                                    "IntegerLiteralExp"},
                                                                                 {value,
                                                                                    1}]}]}]}]}]},
                                                             {content,
                                                                [{expression, "OperationCallExp"},
                                                                 {name, ""},
                                                                 {referredOperation,
                                                                    [{name, "="},
                                                                     {type, [{name, "Boolean"}]}]},
                                                                 {contents,
                                                                    [{content,
                                                                        [{expression,
                                                                            "PropertyCallExp"},
                                                                         {source,
                                                                            [{expression,
                                                                                "OperationCallExp"},
                                                                             {name, ""},
                                                                             {referredOperation,
                                                                                [{name, "at"},
                                                                                 {type,
                                                                                    [{name,
                                                                                        "error"}]}]},
                                                                             {contents,
                                                                                [{content,
                                                                                    [{expression,
                                                                                        "PropertyCallExp"},
                                                                                     {source,
                                                                                        [{expression,
                                                                                            "VariableExp"},
                                                                                         {referredVariable,
                                                                                            [{expression,
                                                                                                "Variable"},
                                                                                             {name,
                                                                                                "result"},
                                                                                             {type,
                                                                                                [{name,
                                                                                                    "createRoomResponse"}]}]}]},
                                                                                     {referredProperty,
                                                                                        [{name,
                                                                                            "errors"},
                                                                                         {type,
                                                                                            [{name,
                                                                                                "Sequence(error)"}]}]}]},
                                                                                 {content,
                                                                                    [{expression,
                                                                                        "IntegerLiteralExp"},
                                                                                     {value,
                                                                                        0}]}]}]},
                                                                         {referredProperty,
                                                                            [{name, "code"},
                                                                             {type,
                                                                                [{name,
                                                                                    "string"}]}]}]},
                                                                     {content,
                                                                        [{expression,
                                                                            "StringLiteralExp"},
                                                                         {value,
                                                                            "required"}]}]}]}]}]},
                                                     {content,
                                                        [{expression, "OperationCallExp"},
                                                         {name, ""},
                                                         {referredOperation,
                                                            [{name, "="},
                                                             {type, [{name, "Boolean"}]}]},
                                                         {contents,
                                                            [{content,
                                                                [{expression, "OperationCallExp"},
                                                                 {name, ""},
                                                                 {referredOperation,
                                                                    [{name, "size"},
                                                                     {type, [{name, "Integer"}]}]},
                                                                 {contents,
                                                                    [{content,
                                                                        [{expression,
                                                                            "PropertyCallExp"},
                                                                         {source,
                                                                            [{expression,
                                                                                "OperationCallExp"},
                                                                             {name, ""},
                                                                             {referredOperation,
                                                                                [{name, "at"},
                                                                                 {type,
                                                                                    [{name,
                                                                                        "error"}]}]},
                                                                             {contents,
                                                                                [{content,
                                                                                    [{expression,
                                                                                        "PropertyCallExp"},
                                                                                     {source,
                                                                                        [{expression,
                                                                                            "VariableExp"},
                                                                                         {referredVariable,
                                                                                            [{expression,
                                                                                                "Variable"},
                                                                                             {name,
                                                                                                "result"},
                                                                                             {type,
                                                                                                [{name,
                                                                                                    "createRoomResponse"}]}]}]},
                                                                                     {referredProperty,
                                                                                        [{name,
                                                                                            "errors"},
                                                                                         {type,
                                                                                            [{name,
                                                                                                "Sequence(error)"}]}]}]},
                                                                                 {content,
                                                                                    [{expression,
                                                                                        "IntegerLiteralExp"},
                                                                                     {value,
                                                                                        0}]}]}]},
                                                                         {referredProperty,
                                                                            [{name, "params"},
                                                                             {type,
                                                                                [{name,
                                                                                    "Sequence(errorParam)"}]}]}]}]}]},
                                                             {content,
                                                                [{expression, "IntegerLiteralExp"},
                                                                 {value, 1}]}]}]}]}]},
                                             {content,
                                                [{expression, "OperationCallExp"},
                                                 {name, ""},
                                                 {referredOperation,
                                                    [{name, "="}, {type, [{name, "Boolean"}]}]},
                                                 {contents,
                                                    [{content,
                                                        [{expression, "PropertyCallExp"},
                                                         {source,
                                                            [{expression, "OperationCallExp"},
                                                             {name, ""},
                                                             {referredOperation,
                                                                [{name, "at"},
                                                                 {type, [{name, "errorParam"}]}]},
                                                             {contents,
                                                                [{content,
                                                                    [{expression,
                                                                        "PropertyCallExp"},
                                                                     {source,
                                                                        [{expression,
                                                                            "OperationCallExp"},
                                                                         {name, ""},
                                                                         {referredOperation,
                                                                            [{name, "at"},
                                                                             {type,
                                                                                [{name,
                                                                                    "error"}]}]},
                                                                         {contents,
                                                                            [{content,
                                                                                [{expression,
                                                                                    "PropertyCallExp"},
                                                                                 {source,
                                                                                    [{expression,
                                                                                        "VariableExp"},
                                                                                     {referredVariable,
                                                                                        [{expression,
                                                                                            "Variable"},
                                                                                         {name,
                                                                                            "result"},
                                                                                         {type,
                                                                                            [{name,
                                                                                                "createRoomResponse"}]}]}]},
                                                                                 {referredProperty,
                                                                                    [{name,
                                                                                        "errors"},
                                                                                     {type,
                                                                                        [{name,
                                                                                            "Sequence(error)"}]}]}]},
                                                                             {content,
                                                                                [{expression,
                                                                                    "IntegerLiteralExp"},
                                                                                 {value, 0}]}]}]},
                                                                     {referredProperty,
                                                                        [{name, "params"},
                                                                         {type,
                                                                            [{name,
                                                                                "Sequence(errorParam)"}]}]}]},
                                                                 {content,
                                                                    [{expression,
                                                                        "IntegerLiteralExp"},
                                                                     {value, 0}]}]}]},
                                                         {referredProperty,
                                                            [{name, "name"},
                                                             {type, [{name, "string"}]}]}]},
                                                     {content,
                                                        [{expression, "StringLiteralExp"},
                                                         {value, "roomId"}]}]}]}]}]},
                                     {content,
                                        [{expression, "OperationCallExp"},
                                         {name, ""},
                                         {referredOperation,
                                            [{name, "="}, {type, [{name, "Boolean"}]}]},
                                         {contents,
                                            [{content,
                                                [{expression, "PropertyCallExp"},
                                                 {source,
                                                    [{expression, "OperationCallExp"},
                                                     {name, ""},
                                                     {referredOperation,
                                                        [{name, "at"},
                                                         {type, [{name, "errorParam"}]}]},
                                                     {contents,
                                                        [{content,
                                                            [{expression, "PropertyCallExp"},
                                                             {source,
                                                                [{expression, "OperationCallExp"},
                                                                 {name, ""},
                                                                 {referredOperation,
                                                                    [{name, "at"},
                                                                     {type, [{name, "error"}]}]},
                                                                 {contents,
                                                                    [{content,
                                                                        [{expression,
                                                                            "PropertyCallExp"},
                                                                         {source,
                                                                            [{expression,
                                                                                "VariableExp"},
                                                                             {referredVariable,
                                                                                [{expression,
                                                                                    "Variable"},
                                                                                 {name, "result"},
                                                                                 {type,
                                                                                    [{name,
                                                                                        "createRoomResponse"}]}]}]},
                                                                         {referredProperty,
                                                                            [{name, "errors"},
                                                                             {type,
                                                                                [{name,
                                                                                    "Sequence(error)"}]}]}]},
                                                                     {content,
                                                                        [{expression,
                                                                            "IntegerLiteralExp"},
                                                                         {value, 0}]}]}]},
                                                             {referredProperty,
                                                                [{name, "params"},
                                                                 {type,
                                                                    [{name,
                                                                        "Sequence(errorParam)"}]}]}]},
                                                         {content,
                                                            [{expression, "IntegerLiteralExp"},
                                                             {value, 0}]}]}]},
                                                 {referredProperty,
                                                    [{name, "value"},
                                                     {type, [{name, "string"}]}]}]},
                                             {content,
                                                [{expression, "StringLiteralExp"},
                                                 {value, ""}]}]}]}]}]},
                             {else,
                                [{expression, "IfExp"},
                                 {condition,
                                    [{expression, "OperationCallExp"},
                                     {name, ""},
                                     {referredOperation,
                                        [{name, "notEmpty"}, {type, [{name, "Boolean"}]}]},
                                     {contents,
                                        [{content,
                                            [{expression, "IteratorExpImpl"},
                                             {name, "select"},
                                             {iterator,
                                                [{variable,
                                                    [{expression, "Variable"},
                                                     {name, "rId"},
                                                     {type, [{name, "String"}]}]}]},
                                             {source,
                                                [{expression, "OperationCallExp"},
                                                 {name, "atPre"},
                                                 {referredOperation,
                                                    [{name, "atPre"},
                                                     {type, [{name, "Sequence(String)"}]}]},
                                                 {contents,
                                                    [{content,
                                                        [{expression, "PropertyCallExp"},
                                                         {source,
                                                            [{expression, "VariableExp"},
                                                             {referredVariable,
                                                                [{expression, "Variable"},
                                                                 {name, "self"},
                                                                 {type, [{name, "VoDKATV"}]}]}]},
                                                         {referredProperty,
                                                            [{name, "state_rooms"},
                                                             {type,
                                                                [{name,
                                                                    "Sequence(String)"}]}]}]}]}]},
                                             {body,
                                                [{expression, "OperationCallExp"},
                                                 {name, ""},
                                                 {referredOperation,
                                                    [{name, "="}, {type, [{name, "Boolean"}]}]},
                                                 {contents,
                                                    [{content,
                                                        [{expression, "VariableExp"},
                                                         {referredVariable,
                                                            [{expression, "Variable"},
                                                             {name, "rId"},
                                                             {type, [{name, "String"}]}]}]},
                                                     {content,
                                                        [{expression, "VariableExp"},
                                                         {referredVariable,
                                                            [{expression, "Variable"},
                                                             {name, "roomId"},
                                                             {type,
                                                                [{name, "string"}]}]}]}]}]}]}]}]},
                                 {then,
                                    [{expression, "OperationCallExp"},
                                     {name, ""},
                                     {referredOperation,
                                        [{name, "and"}, {type, [{name, "Boolean"}]}]},
                                     {contents,
                                        [{content,
                                            [{expression, "OperationCallExp"},
                                             {name, ""},
                                             {referredOperation,
                                                [{name, "and"}, {type, [{name, "Boolean"}]}]},
                                             {contents,
                                                [{content,
                                                    [{expression, "OperationCallExp"},
                                                     {name, ""},
                                                     {referredOperation,
                                                        [{name, "and"},
                                                         {type, [{name, "Boolean"}]}]},
                                                     {contents,
                                                        [{content,
                                                            [{expression, "OperationCallExp"},
                                                             {name, ""},
                                                             {referredOperation,
                                                                [{name, "and"},
                                                                 {type, [{name, "Boolean"}]}]},
                                                             {contents,
                                                                [{content,
                                                                    [{expression,
                                                                        "OperationCallExp"},
                                                                     {name, ""},
                                                                     {referredOperation,
                                                                        [{name, "and"},
                                                                         {type,
                                                                            [{name, "Boolean"}]}]},
                                                                     {contents,
                                                                        [{content,
                                                                            [{expression,
                                                                                "OperationCallExp"},
                                                                             {name, ""},
                                                                             {referredOperation,
                                                                                [{name, "="},
                                                                                 {type,
                                                                                    [{name,
                                                                                        "Boolean"}]}]},
                                                                             {contents,
                                                                                [{content,
                                                                                    [{expression,
                                                                                        "PropertyCallExp"},
                                                                                     {source,
                                                                                        [{expression,
                                                                                            "VariableExp"},
                                                                                         {referredVariable,
                                                                                            [{expression,
                                                                                                "Variable"},
                                                                                             {name,
                                                                                                "self"},
                                                                                             {type,
                                                                                                [{name,
                                                                                                    "VoDKATV"}]}]}]},
                                                                                     {referredProperty,
                                                                                        [{name,
                                                                                            "state_rooms"},
                                                                                         {type,
                                                                                            [{name,
                                                                                                "Sequence(String)"}]}]}]},
                                                                                 {content,
                                                                                    [{expression,
                                                                                        "OperationCallExp"},
                                                                                     {name,
                                                                                        "atPre"},
                                                                                     {referredOperation,
                                                                                        [{name,
                                                                                            "atPre"},
                                                                                         {type,
                                                                                            [{name,
                                                                                                "Sequence(String)"}]}]},
                                                                                     {contents,
                                                                                        [{content,
                                                                                            [{expression,
                                                                                                "PropertyCallExp"},
                                                                                             {source,
                                                                                                [{expression,
                                                                                                    "VariableExp"},
                                                                                                 {referredVariable,
                                                                                                    [{expression,
                                                                                                        "Variable"},
                                                                                                     {name,
                                                                                                        "self"},
                                                                                                     {type,
                                                                                                        [{name,
                                                                                                            "VoDKATV"}]}]}]},
                                                                                             {referredProperty,
                                                                                                [{name,
                                                                                                    "state_rooms"},
                                                                                                 {type,
                                                                                                    [{name,
                                                                                                        "Sequence(String)"}]}]}]}]}]}]}]},
                                                                         {content,
                                                                            [{expression,
                                                                                "OperationCallExp"},
                                                                             {name, ""},
                                                                             {referredOperation,
                                                                                [{name, "="},
                                                                                 {type,
                                                                                    [{name,
                                                                                        "Boolean"}]}]},
                                                                             {contents,
                                                                                [{content,
                                                                                    [{expression,
                                                                                        "OperationCallExp"},
                                                                                     {name, ""},
                                                                                     {referredOperation,
                                                                                        [{name,
                                                                                            "size"},
                                                                                         {type,
                                                                                            [{name,
                                                                                                "Integer"}]}]},
                                                                                     {contents,
                                                                                        [{content,
                                                                                            [{expression,
                                                                                                "PropertyCallExp"},
                                                                                             {source,
                                                                                                [{expression,
                                                                                                    "VariableExp"},
                                                                                                 {referredVariable,
                                                                                                    [{expression,
                                                                                                        "Variable"},
                                                                                                     {name,
                                                                                                        "result"},
                                                                                                     {type,
                                                                                                        [{name,
                                                                                                            "createRoomResponse"}]}]}]},
                                                                                             {referredProperty,
                                                                                                [{name,
                                                                                                    "errors"},
                                                                                                 {type,
                                                                                                    [{name,
                                                                                                        "Sequence(error)"}]}]}]}]}]},
                                                                                 {content,
                                                                                    [{expression,
                                                                                        "IntegerLiteralExp"},
                                                                                     {value,
                                                                                        1}]}]}]}]}]},
                                                                 {content,
                                                                    [{expression,
                                                                        "OperationCallExp"},
                                                                     {name, ""},
                                                                     {referredOperation,
                                                                        [{name, "="},
                                                                         {type,
                                                                            [{name, "Boolean"}]}]},
                                                                     {contents,
                                                                        [{content,
                                                                            [{expression,
                                                                                "PropertyCallExp"},
                                                                             {source,
                                                                                [{expression,
                                                                                    "OperationCallExp"},
                                                                                 {name, ""},
                                                                                 {referredOperation,
                                                                                    [{name, "at"},
                                                                                     {type,
                                                                                        [{name,
                                                                                            "error"}]}]},
                                                                                 {contents,
                                                                                    [{content,
                                                                                        [{expression,
                                                                                            "PropertyCallExp"},
                                                                                         {source,
                                                                                            [{expression,
                                                                                                "VariableExp"},
                                                                                             {referredVariable,
                                                                                                [{expression,
                                                                                                    "Variable"},
                                                                                                 {name,
                                                                                                    "result"},
                                                                                                 {type,
                                                                                                    [{name,
                                                                                                        "createRoomResponse"}]}]}]},
                                                                                         {referredProperty,
                                                                                            [{name,
                                                                                                "errors"},
                                                                                             {type,
                                                                                                [{name,
                                                                                                    "Sequence(error)"}]}]}]},
                                                                                     {content,
                                                                                        [{expression,
                                                                                            "IntegerLiteralExp"},
                                                                                         {value,
                                                                                            0}]}]}]},
                                                                             {referredProperty,
                                                                                [{name, "code"},
                                                                                 {type,
                                                                                    [{name,
                                                                                        "string"}]}]}]},
                                                                         {content,
                                                                            [{expression,
                                                                                "StringLiteralExp"},
                                                                             {value,
                                                                                "duplicated"}]}]}]}]}]},
                                                         {content,
                                                            [{expression, "OperationCallExp"},
                                                             {name, ""},
                                                             {referredOperation,
                                                                [{name, "="},
                                                                 {type, [{name, "Boolean"}]}]},
                                                             {contents,
                                                                [{content,
                                                                    [{expression,
                                                                        "OperationCallExp"},
                                                                     {name, ""},
                                                                     {referredOperation,
                                                                        [{name, "size"},
                                                                         {type,
                                                                            [{name, "Integer"}]}]},
                                                                     {contents,
                                                                        [{content,
                                                                            [{expression,
                                                                                "PropertyCallExp"},
                                                                             {source,
                                                                                [{expression,
                                                                                    "OperationCallExp"},
                                                                                 {name, ""},
                                                                                 {referredOperation,
                                                                                    [{name, "at"},
                                                                                     {type,
                                                                                        [{name,
                                                                                            "error"}]}]},
                                                                                 {contents,
                                                                                    [{content,
                                                                                        [{expression,
                                                                                            "PropertyCallExp"},
                                                                                         {source,
                                                                                            [{expression,
                                                                                                "VariableExp"},
                                                                                             {referredVariable,
                                                                                                [{expression,
                                                                                                    "Variable"},
                                                                                                 {name,
                                                                                                    "result"},
                                                                                                 {type,
                                                                                                    [{name,
                                                                                                        "createRoomResponse"}]}]}]},
                                                                                         {referredProperty,
                                                                                            [{name,
                                                                                                "errors"},
                                                                                             {type,
                                                                                                [{name,
                                                                                                    "Sequence(error)"}]}]}]},
                                                                                     {content,
                                                                                        [{expression,
                                                                                            "IntegerLiteralExp"},
                                                                                         {value,
                                                                                            0}]}]}]},
                                                                             {referredProperty,
                                                                                [{name, "params"},
                                                                                 {type,
                                                                                    [{name,
                                                                                        "Sequence(errorParam)"}]}]}]}]}]},
                                                                 {content,
                                                                    [{expression,
                                                                        "IntegerLiteralExp"},
                                                                     {value, 1}]}]}]}]}]},
                                                 {content,
                                                    [{expression, "OperationCallExp"},
                                                     {name, ""},
                                                     {referredOperation,
                                                        [{name, "="}, {type, [{name, "Boolean"}]}]},
                                                     {contents,
                                                        [{content,
                                                            [{expression, "PropertyCallExp"},
                                                             {source,
                                                                [{expression, "OperationCallExp"},
                                                                 {name, ""},
                                                                 {referredOperation,
                                                                    [{name, "at"},
                                                                     {type,
                                                                        [{name, "errorParam"}]}]},
                                                                 {contents,
                                                                    [{content,
                                                                        [{expression,
                                                                            "PropertyCallExp"},
                                                                         {source,
                                                                            [{expression,
                                                                                "OperationCallExp"},
                                                                             {name, ""},
                                                                             {referredOperation,
                                                                                [{name, "at"},
                                                                                 {type,
                                                                                    [{name,
                                                                                        "error"}]}]},
                                                                             {contents,
                                                                                [{content,
                                                                                    [{expression,
                                                                                        "PropertyCallExp"},
                                                                                     {source,
                                                                                        [{expression,
                                                                                            "VariableExp"},
                                                                                         {referredVariable,
                                                                                            [{expression,
                                                                                                "Variable"},
                                                                                             {name,
                                                                                                "result"},
                                                                                             {type,
                                                                                                [{name,
                                                                                                    "createRoomResponse"}]}]}]},
                                                                                     {referredProperty,
                                                                                        [{name,
                                                                                            "errors"},
                                                                                         {type,
                                                                                            [{name,
                                                                                                "Sequence(error)"}]}]}]},
                                                                                 {content,
                                                                                    [{expression,
                                                                                        "IntegerLiteralExp"},
                                                                                     {value,
                                                                                        0}]}]}]},
                                                                         {referredProperty,
                                                                            [{name, "params"},
                                                                             {type,
                                                                                [{name,
                                                                                    "Sequence(errorParam)"}]}]}]},
                                                                     {content,
                                                                        [{expression,
                                                                            "IntegerLiteralExp"},
                                                                         {value, 0}]}]}]},
                                                             {referredProperty,
                                                                [{name, "name"},
                                                                 {type, [{name, "string"}]}]}]},
                                                         {content,
                                                            [{expression, "StringLiteralExp"},
                                                             {value, "roomId"}]}]}]}]}]},
                                         {content,
                                            [{expression, "OperationCallExp"},
                                             {name, ""},
                                             {referredOperation,
                                                [{name, "="}, {type, [{name, "Boolean"}]}]},
                                             {contents,
                                                [{content,
                                                    [{expression, "PropertyCallExp"},
                                                     {source,
                                                        [{expression, "OperationCallExp"},
                                                         {name, ""},
                                                         {referredOperation,
                                                            [{name, "at"},
                                                             {type, [{name, "errorParam"}]}]},
                                                         {contents,
                                                            [{content,
                                                                [{expression, "PropertyCallExp"},
                                                                 {source,
                                                                    [{expression,
                                                                        "OperationCallExp"},
                                                                     {name, ""},
                                                                     {referredOperation,
                                                                        [{name, "at"},
                                                                         {type,
                                                                            [{name, "error"}]}]},
                                                                     {contents,
                                                                        [{content,
                                                                            [{expression,
                                                                                "PropertyCallExp"},
                                                                             {source,
                                                                                [{expression,
                                                                                    "VariableExp"},
                                                                                 {referredVariable,
                                                                                    [{expression,
                                                                                        "Variable"},
                                                                                     {name,
                                                                                        "result"},
                                                                                     {type,
                                                                                        [{name,
                                                                                            "createRoomResponse"}]}]}]},
                                                                             {referredProperty,
                                                                                [{name, "errors"},
                                                                                 {type,
                                                                                    [{name,
                                                                                        "Sequence(error)"}]}]}]},
                                                                         {content,
                                                                            [{expression,
                                                                                "IntegerLiteralExp"},
                                                                             {value, 0}]}]}]},
                                                                 {referredProperty,
                                                                    [{name, "params"},
                                                                     {type,
                                                                        [{name,
                                                                            "Sequence(errorParam)"}]}]}]},
                                                             {content,
                                                                [{expression, "IntegerLiteralExp"},
                                                                 {value, 0}]}]}]},
                                                     {referredProperty,
                                                        [{name, "value"},
                                                         {type, [{name, "string"}]}]}]},
                                                 {content,
                                                    [{expression, "VariableExp"},
                                                     {referredVariable,
                                                        [{expression, "Variable"},
                                                         {name, "roomId"},
                                                         {type, [{name, "string"}]}]}]}]}]}]}]},
                                 {else,
                                    [{expression, "OperationCallExp"},
                                     {name, ""},
                                     {referredOperation,
                                        [{name, "and"}, {type, [{name, "Boolean"}]}]},
                                     {contents,
                                        [{content,
                                            [{expression, "OperationCallExp"},
                                             {name, ""},
                                             {referredOperation,
                                                [{name, "and"}, {type, [{name, "Boolean"}]}]},
                                             {contents,
                                                [{content,
                                                    [{expression, "OperationCallExp"},
                                                     {name, ""},
                                                     {referredOperation,
                                                        [{name, "="}, {type, [{name, "Boolean"}]}]},
                                                     {contents,
                                                        [{content,
                                                            [{expression, "PropertyCallExp"},
                                                             {source,
                                                                [{expression, "VariableExp"},
                                                                 {referredVariable,
                                                                    [{expression, "Variable"},
                                                                     {name, "self"},
                                                                     {type,
                                                                        [{name, "VoDKATV"}]}]}]},
                                                             {referredProperty,
                                                                [{name, "state_rooms"},
                                                                 {type,
                                                                    [{name,
                                                                        "Sequence(String)"}]}]}]},
                                                         {content,
                                                            [{expression, "OperationCallExp"},
                                                             {name, ""},
                                                             {referredOperation,
                                                                [{name, "including"},
                                                                 {type,
                                                                    [{name, "Sequence(String)"}]}]},
                                                             {contents,
                                                                [{content,
                                                                    [{expression,
                                                                        "OperationCallExp"},
                                                                     {name, "atPre"},
                                                                     {referredOperation,
                                                                        [{name, "atPre"},
                                                                         {type,
                                                                            [{name,
                                                                                "Sequence(String)"}]}]},
                                                                     {contents,
                                                                        [{content,
                                                                            [{expression,
                                                                                "PropertyCallExp"},
                                                                             {source,
                                                                                [{expression,
                                                                                    "VariableExp"},
                                                                                 {referredVariable,
                                                                                    [{expression,
                                                                                        "Variable"},
                                                                                     {name, "self"},
                                                                                     {type,
                                                                                        [{name,
                                                                                            "VoDKATV"}]}]}]},
                                                                             {referredProperty,
                                                                                [{name,
                                                                                    "state_rooms"},
                                                                                 {type,
                                                                                    [{name,
                                                                                        "Sequence(String)"}]}]}]}]}]},
                                                                 {content,
                                                                    [{expression, "VariableExp"},
                                                                     {referredVariable,
                                                                        [{expression, "Variable"},
                                                                         {name, "roomId"},
                                                                         {type,
                                                                            [{name,
                                                                                "string"}]}]}]}]}]}]}]},
                                                 {content,
                                                    [{expression, "OperationCallExp"},
                                                     {name, ""},
                                                     {referredOperation,
                                                        [{name, "="}, {type, [{name, "Boolean"}]}]},
                                                     {contents,
                                                        [{content,
                                                            [{expression, "PropertyCallExp"},
                                                             {source,
                                                                [{expression, "VariableExp"},
                                                                 {referredVariable,
                                                                    [{expression, "Variable"},
                                                                     {name, "result"},
                                                                     {type,
                                                                        [{name,
                                                                            "createRoomResponse"}]}]}]},
                                                             {referredProperty,
                                                                [{name, "roomId"},
                                                                 {type, [{name, "string"}]}]}]},
                                                         {content,
                                                            [{expression, "VariableExp"},
                                                             {referredVariable,
                                                                [{expression, "Variable"},
                                                                 {name, "roomId"},
                                                                 {type,
                                                                    [{name, "string"}]}]}]}]}]}]}]},
                                         {content,
                                            [{expression, "OperationCallExp"},
                                             {name, ""},
                                             {referredOperation,
                                                [{name, "="}, {type, [{name, "Boolean"}]}]},
                                             {contents,
                                                [{content,
                                                    [{expression, "PropertyCallExp"},
                                                     {source,
                                                        [{expression, "VariableExp"},
                                                         {referredVariable,
                                                            [{expression, "Variable"},
                                                             {name, "result"},
                                                             {type,
                                                                [{name, "createRoomResponse"}]}]}]},
                                                     {referredProperty,
                                                        [{name, "description"},
                                                         {type, [{name, "string"}]}]}]},
                                                 {content,
                                                    [{expression, "VariableExp"},
                                                     {referredVariable,
                                                        [{expression, "Variable"},
                                                         {name, "description"},
                                                         {type,
                                                            [{name, "string"}]}]}]}]}]}]}]}]}]}]}]},
                 {invariants, []}]}]}]}]},
 {class,
    [{name, "createRoomParams"},
     {constraints, [{invariants, []}]},
     {attributes,
        [{attribute, [{name, "roomId"}, {type, [{name, "string"}]}]},
         {attribute, [{name, "description"}, {type, [{name, "string"}]}]}]},
     {operations, []}]},
 {class,
    [{name, "createRoomResponse"},
     {constraints, [{invariants, []}]},
     {attributes,
        [{attribute, [{name, "roomId"}, {type, [{name, "string"}]}]},
         {attribute, [{name, "description"}, {type, [{name, "string"}]}]},
         {attribute,
            [{name, "errors"}, {type, [{name, "Sequence(error)"}]}]}]},
     {operations, []}]},
 {class,
    [{name, "error"},
     {constraints, [{invariants, []}]},
     {attributes,
        [{attribute, [{name, "code"}, {type, [{name, "string"}]}]},
         {attribute,
            [{name, "params"}, {type, [{name, "Sequence(errorParam)"}]}]},
         {attribute, [{name, "description"}, {type, [{name, "string"}]}]}]},
     {operations, []}]},
 {class,
    [{name, "errorParam"},
     {constraints, [{invariants, []}]},
     {attributes,
        [{attribute, [{name, "name"}, {type, [{name, "string"}]}]},
         {attribute, [{name, "value"}, {type, [{name, "string"}]}]}]},
     {operations, []}]}].
